<body>
	<div class="container">
	<div class="top">
		<img src="images/peas.gif" alt="peas" />
		<div class="center">
			<h1>Clean Eats</h1>
			<h2>The journey to clean eating</h2>
		</div>
		<div id="nav">
			<ul>
				<li><a <?php if ($current_page == "home") { ?>class="special"<?php } ?>href="index.php">Home </a>|</li>
				<li><a <?php if ($current_page == "recipes") { ?>class="special"<?php } ?>href="recipes.php">Recipes </a>|</li>
				<li><a <?php if ($current_page == "whatIs") { ?>class="special"<?php } ?>href="clean_eating.php">What is Clean Eating? </a>|</li>
				<li><a <?php if ($current_page == "contact") { ?>class="special"<?php } ?>href="contact.php">Contact </a>|</li>
				<li><a <?php if ($current_page == "about") { ?>class="special"<?php } ?>href="about.php">About </a>|</li>
				<li><a <?php if ($current_page == "products") { ?>class="special"<?php } ?>href="products.php">Products</a></li>

			</ul>
		</div><!-- end of nav -->
	</div><!-- top end -->
		
				
	
<!--begin second half -->
    <div class="center" id="sidebar"> 
    
    <a href="http://www.twitter.com/mlgospo"><img src="http://twitter-badges.s3.amazonaws.com/follow_me-a.png" alt="Follow me on Twitter"/></a><br /><br />
    			
    <!-- Facebook Badge START -->
    <a href="http://www.facebook.com/people/Marsha-Gospodarek/665937511" target="_TOP" title="Marsha Gospodarek"><img src="http://badge.facebook.com/badge/665937511.3174.1141910155.png" width="120" height="222" style="border: 0px;" /></a><br/>
    <!-- Facebook Badge END -->
    			
    			
    <h1 id="quote">"You can't out exercise poor eating habits." - unknown</h1>
    
	<div id="cloud"><!--
			begin tag cloud : generated by TagCrowd.com
			Feel free to modify as long as you keep this notice.
			
			EMBEDDING INSTRUCTIONS:
			1. Customize your cloud's style by editing the CSS where it says CUSTOMIZE below.
			2. Insert this code in its entirety into your webpage or blog post.
			
			This code and its rendered image are released under the Creative Commons Attribution-Noncommercial 3.0 Unported License. (http://creativecommons.org/licenses/by-nc/3.0/)
			
			For COMMERCIAL USE LICENSING, visit http://tagcrowd.com/licensing.html
			-->
			<style type="text/css"><!-- #htmltagcloud{
			
			/******************************************
			 * CUSTOMIZE CLOUD CSS BELOW (optional)
			 */
				
			/******************************************
			 * END CUSTOMIZE
			 */
	
			}#htmltagcloud{line-height:2.4em;word-spacing:normal;letter-spacing:normal;text-transform:none;text-align:justify;text-indent:0}#htmltagcloud a:link{text-decoration:none}#htmltagcloud a:visited{text-decoration:none}#htmltagcloud a:hover{color:white;background-color:#05f}#htmltagcloud a:active{color:white;background-color:#03d}.wrd{:0;position:relative}.wrd a{text-decoration:none}.tagcloud0{font-size:1.0em;color:#ACC1F3;z-index:10}.tagcloud0 a{color:#ACC1F3}.tagcloud1{font-size:1.4em;color:#ACC1F3;z-index:9}.tagcloud1 a{color:#ACC1F3}.tagcloud2{font-size:1.8em;color:#86A0DC;z-index:8}.tagcloud2 a{color:#86A0DC}.tagcloud3{font-size:2.2em;color:#86A0DC;z-index:7}.tagcloud3 a{color:#86A0DC}.tagcloud4{font-size:2.6em;color:#607EC5;z-index:6}.tagcloud4 a{color:#607EC5}.tagcloud5{font-size:3.0em;color:#607EC5;z-index:5}.tagcloud5 a{color:#607EC5}.tagcloud6{font-size:3.3em;color:#4C6DB9;z-index:4}.tagcloud6 a{color:#4C6DB9}.tagcloud7{font-size:3.6em;color:#395CAE;z-index:3}.tagcloud7 a{color:#395CAE}.tagcloud8{font-size:3.9em;color:#264CA2;z-index:2}.tagcloud8 a{color:#264CA2}.tagcloud9{font-size:4.2em;color:#133B97;z-index:1}.tagcloud9 a{color:#133B97}.tagcloud10{font-size:4.5em;color:#002A8B;z-index:0}.tagcloud10 a{color:#002A8B}.freq{font-size:10pt !important;color:#bbb}#credit{text-align:center;color:#333;margin-bottom:0.6em;font:0.7em 'lucida grande',trebuchet,'trebuchet ms',verdana,arial,helvetica,sans-serif}#credit a:link{color:#777;text-decoration:none}#credit a:visited{color:#777;text-decoration:none}#credit a:hover{color:white;background-color:#05f}#credit a:active{text-decoration:underline}// -->
			</style>
			
			<div id="htmltagcloud"> <span id="0" class="wrd tagcloud0"><a href="#tagcloud">-5555</a></span> <span id="1" class="wrd tagcloud0"><a href="#tagcloud">16th</a></span> <span id="2" class="wrd tagcloud0"><a href="#tagcloud">area</a></span> <span id="3" class="wrd tagcloud0"><a href="#tagcloud">attractions</a></span> <span id="4" class="wrd tagcloud0"><a href="#tagcloud">com</a></span> <span id="5" class="wrd tagcloud0"><a href="#tagcloud">comments</a></span> <span id="6" class="wrd tagcloud5"><a href="#tagcloud">condo</a></span> <span id="7" class="wrd tagcloud0"><a href="#tagcloud">contact</a></span> <span id="8" class="wrd tagcloud0"><a href="#tagcloud">coors</a></span> <span id="9" class="wrd tagcloud0"><a href="#tagcloud">copyright</a></span> <span id="10" class="wrd tagcloud0"><a href="#tagcloud">ddrentals</a></span> <span id="11" class="wrd tagcloud7"><a href="#tagcloud">denver</a></span> <span id="12" class="wrd tagcloud0"><a href="#tagcloud">denverrentals</a></span> <span id="13" class="wrd tagcloud0"><a href="#tagcloud">designed</a></span> <span id="14" class="wrd tagcloud0"><a href="#tagcloud">distance</a></span> <span id="15" class="wrd tagcloud5"><a href="#tagcloud">downtown</a></span> <span id="16" class="wrd tagcloud0"><a href="#tagcloud">downtowndenverrentals</a></span> <span id="17" class="wrd tagcloud0"><a href="#tagcloud">experience</a></span> <span id="18" class="wrd tagcloud0"><a href="#tagcloud">field</a></span> <span id="19" class="wrd tagcloud0"><a href="#tagcloud">gmail</a></span> <span id="20" class="wrd tagcloud5"><a href="#tagcloud">home</a></span> <span id="21" class="wrd tagcloud0"><a href="#tagcloud">including</a></span> <span id="22" class="wrd tagcloud0"><a href="#tagcloud">liab</a></span> <span id="23" class="wrd tagcloud0"><a href="#tagcloud">lightrail</a></span> <span id="24" class="wrd tagcloud5"><a href="#tagcloud">lodo</a></span> <span id="25" class="wrd tagcloud0"><a href="#tagcloud">luxurious</a></span> <span id="26" class="wrd tagcloud0"><a href="#tagcloud">main</a></span> <span id="27" class="wrd tagcloud0"><a href="#tagcloud">mall</a></span> <span id="28" class="wrd tagcloud0"><a href="#tagcloud">offer</a></span> <span id="29" class="wrd tagcloud0"><a href="#tagcloud">owntown</a></span> <span id="30" class="wrd tagcloud0"><a href="#tagcloud">personalized</a></span> <span id="31" class="wrd tagcloud0"><a href="#tagcloud">please</a></span> <span id="32" class="wrd tagcloud0"><a href="#tagcloud">properties</a></span> <span id="33" class="wrd tagcloud0"><a href="#tagcloud">pubs</a></span> <span id="34" class="wrd tagcloud0"><a href="#tagcloud">questions</a></span> <span id="35" class="wrd tagcloud0"><a href="#tagcloud">rates</a></span> <span id="36" class="wrd tagcloud10"><a href="#tagcloud">rentals</a></span> <span id="37" class="wrd tagcloud0"><a href="#tagcloud">restaurants</a></span> <span id="38" class="wrd tagcloud0"><a href="#tagcloud">shops</a></span> <span id="39" class="wrd tagcloud0"><a href="#tagcloud">short-term</a></span> <span id="40" class="wrd tagcloud0"><a href="#tagcloud">stays</a></span> <span id="41" class="wrd tagcloud0"><a href="#tagcloud">street</a></span> <span id="42" class="wrd tagcloud10"><a href="#tagcloud">uptown</a></span> <span id="43" class="wrd tagcloud0"><a href="#tagcloud">walking</a></span> <span id="44" class="wrd tagcloud0"><a href="#tagcloud">website</a></span> <span id="45" class="wrd tagcloud5"><a href="#tagcloud">welcome</a></span> </div><div id="credit">created at <a href="http://tagcrowd.com">TagCrowd.com</a></div>
	
	<!-- end tag cloud : generated by TagCrowd.com : please keep this notice -->
	</div><!--end cloud div-->

	<div class="rounded-corners" id="food_gallery">
	    	<h3>Food Gallery</h3>		
	
		<a href="images/fullscreen/Veggie Chili_fullscreen.jpg" rel="prettyPhoto[pp_gal]" ><img src="images/thumbnails/Veggie Chili_thumbnail.jpg" width="60" height="60" alt="Veggie Chili" /></a>
		<a href="images/fullscreen/Lentil Sloppy Joes_fullscreen.jpg" rel="prettyPhoto[pp_gal]"><img src="images/thumbnails/Lentil Sloppy Joes.jpg" width="60" height="60" alt="Lentil Sloppy Joes" /></a>
	
		<a href="images/fullscreen/Moroccan Lentil Stew_fullscreen.jpg" rel="prettyPhoto[pp_gal]"><img src="images/thumbnails/Moroccan Lentil Stew.jpg" width="60" height="60" alt="Moroccan Lentil Stew" /></a>
	
		<a href="images/fullscreen/4.jpg" rel="prettyPhoto[pp_gal]"><img src="images/thumbnails/t_4.jpg" width="60" height="60" alt="Rock climbing" /></a>
	
		<a href="images/fullscreen/5.jpg" rel="prettyPhoto[pp_gal]"><img src="images/thumbnails/t_5.jpg" width="60" height="60" alt="Fly kite, fly!" /></a>
	</div>   
	
	<div id="newsletter">
		<p><a href="contact.php">Sign up for newsletter</a></p>
	</div>
	
</div> <!--  end sidebar -->
    			
